blueprint:
  name: Aqara Double Switch
  description: 'Blueprint for Home Assistant for the Xiaomi Aqara double key wireless wall switch using zigbee2mqtt.'
  domain: automation
  input:
    switch:
      name: Switch
      description: Action sensor of Aqara Wireless Switch to use
      selector:
        entity:
          domain: sensor
          integration: mqtt

    press_single_left:
      name: Single left button press
      description: Action to run on single left button press
      default: []
      selector:
        action: {}

    press_double_left:
      name: Double left button press
      description: Action to run on double left button press
      default: []
      selector:
        action: {}

    press_hold_left:
      name: Hold left button
      description: Action to run on holding left button
      default: []
      selector:
        action: {}

    press_single_right:
      name: Single right button press
      description: Action to run on single right button press
      default: []
      selector:
        action: {}

    press_double_right:
      name: Double right button press
      description: Action to run on double right button press
      default: []
      selector:
        action: {}

    press_hold_right:
      name: Hold right button
      description: Action to run on holding right button
      default: []
      selector:
        action: {}

    press_single_both:
      name: Single both buttons press
      description: Action to run on single both button press
      default: []
      selector:
        action: {}

    press_double_both:
      name: Double both buttons press
      description: Action to run on double both button press
      default: []
      selector:
        action: {}

    press_hold_both:
      name: Hold both buttons
      description: Action to run on holding both buttons
      default: []
      selector:
        action: {}


mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input switch
    #attribute: click

#  , single_right, single_both, , , double_both, , hold_right, hold_both.

action:
  - variables:
      command: "{{ trigger.to_state.state }}"

  - choose:
      - conditions:
          - "{{ command == 'single_left' }}"
        sequence: !input press_single_left
      - conditions:
          - "{{ command == 'double_left' }}"
        sequence: !input press_double_left
      - conditions:
          - "{{ command == 'hold_left' }}"
        sequence: !input press_hold_left

      - conditions:
          - "{{ command == 'single_right' }}"
        sequence: !input press_single_right
      - conditions:
          - "{{ command == 'double_right' }}"
        sequence: !input press_double_right
      - conditions:
          - "{{ command == 'hold_right' }}"
        sequence: !input press_hold_right

      - conditions:
          - "{{ command == 'single_both' }}"
        sequence: !input press_single_right
      - conditions:
          - "{{ command == 'double_both' }}"
        sequence: !input press_double_right
      - conditions:
          - "{{ command == 'hold_both' }}"
        sequence: !input press_hold_right